Data Structures, Functions, Numpy & Pandas

Section A: Data Structures & Control Structures

Q.1)

In [13]:
lst=[10,20,30,40,50]
lst.append(60)
lst

[10, 20, 30, 40, 50, 60]

In [14]:
lst.extend([70,80])

In [15]:
lst

[10, 20, 30, 40, 50, 60, 70, 80]

In [16]:
lst.insert(99,4)

In [17]:
lst

[10, 20, 30, 40, 50, 60, 70, 80, 4]

In [18]:
lst.pop()

4

In [19]:
lst.pop(4)
lst

[10, 20, 30, 40, 60, 70, 80]

In [20]:
lst.insert(3,5)
lst

[10, 20, 30, 5, 40, 60, 70, 80]

In [23]:
lst.index(60)

5

In [26]:
lst.count(10)
lst

[10, 20, 30, 5, 40, 60, 70, 80]

In [28]:
lst.sort()
lst

[5, 10, 20, 30, 40, 60, 70, 80]

In [29]:
lst.sort(reverse=True)
lst

[80, 70, 60, 40, 30, 20, 10, 5]

In [30]:
lst.remove(10)
lst

[80, 70, 60, 40, 30, 20, 5]

In [31]:
lst.clear()
lst

[]

Q.2)

In [34]:
tupl=("Ram","Tom","Sam")
tupl[1]="kiran"  
#### tuple is immutable : the values once assigned cant be changed

TypeError: 'tuple' object does not support item assignment

Q.3)

In [37]:
setss={1,2,2,2,3,3,4,4,5}
print(setss) 
#### set which allows only the unique values and it does not allow duplicate values

{1, 2, 3, 4, 5}


Q.4)

In [40]:
dict={'name':"Ram",'age':18,'city':"bangalore"}
dict['age']=21
dict['email']='kros@gmail.com'

In [41]:
dict

{'name': 'Ram', 'age': 21, 'city': 'bangalore', 'email': 'kros@gmail.com'}

Q.5)

In [42]:
age=int(input("enter the age:"))
if (age<18):
    print("Not eligible to vote")
else:
    print("eligible to vote")

    
    

enter the age: 18


eligible to vote


Q.6)

In [45]:
marks=int(input("Enter the marks:"))
if marks>=90:
    print("grade A")
elif marks>=75 and marks<=89:
    print("grade B")
elif marks>=50 and marks<=74:
    print("grade C")
else:
    print("Fail")


Enter the marks: 65


grade C


Q.7)

In [51]:
n=int(input("Enter the no:"))
if n>0 and n%2==0:
    print("positive and even no")
elif n==0:
    print("zero")
else:
    print("negative and odd no")

Enter the no: 3


negative and odd no


Section B: Numpy

Q.8)

In [53]:
import numpy as np
scaler=np.array(5)
scaler

array(5)

In [54]:
arr1=np.array([1,2,3,4,5])
print("arr1:",arr1)

arr1: [1 2 3 4 5]


In [58]:
arr2=np.array([[10,20,30],[40,50,60]])
print("arr2:",arr2)

arr2: [[10 20 30]
 [40 50 60]]


Q.9)

In [62]:
rand_array=np.random.randint(0,100,(4,4))
print(rand_array)

[[59 36  5 53]
 [73 26 73  2]
 [34 52 66 69]
 [37  1 94 19]]


Q.10)

In [67]:
import pandas as pd
arr3=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(arr3)
df=pd.DataFrame(arr3,columns=['A','B','C'])
df

[[10 11 12]
 [13 14 15]
 [16 17 18]]


,A,B,C
0,10,11,12
1,13,14,15
2,16,17,18


Section C: Exploring Pandas

Q.11)

In [69]:
data={"Name": ["Amit", "Riya", "John", "Neha", "Arun",
             "Riya", "Sita", "Karan", "Meena", "Amit"],
    "Age": [25, 22, 28, 24, 30, 22, 27, 26, 29, 25],
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "Pune",
             "Mumbai", "Kolkata", "Bangalore", "Delhi", "Delhi"],
    "Salary": [40000, 35000, 50000, 42000, 25000,
               35000, 48000, 45000, 52000, 40000]}
df=pd.DataFrame(data)
df

,Name,Age,City,Salary
0,Amit,25,Delhi,40000
1,Riya,22,Mumbai,35000
2,John,28,Chennai,50000
3,Neha,24,Delhi,42000
4,Arun,30,Pune,25000
5,Riya,22,Mumbai,35000
6,Sita,27,Kolkata,48000
7,Karan,26,Bangalore,45000
8,Meena,29,Delhi,52000
9,Amit,25,Delhi,40000


In [70]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


,Age,Salary
count,10.000000,10.000000
mean,25.800000,41200.000000
std,2.740641,8148.619515
min,22.000000,25000.000000
25%,24.250000,36250.000000
50%,25.500000,41000.000000
75%,27.750000,47250.000000
max,30.000000,52000.000000


In [76]:
print(df['Name'],df['City'])

0     Amit
1     Riya
2     John
3     Neha
4     Arun
5     Riya
6     Sita
7    Karan
8    Meena
9     Amit
Name: Name, dtype: object 0        Delhi
1       Mumbai
2      Chennai
3        Delhi
4         Pune
5       Mumbai
6      Kolkata
7    Bangalore
8        Delhi
9        Delhi
Name: City, dtype: object


In [81]:
df.drop('City',axis=1)


,Name,Age,Salary
0,Amit,25,40000
1,Riya,22,35000
2,John,28,50000
3,Neha,24,42000
4,Arun,30,25000
5,Riya,22,35000
6,Sita,27,48000
7,Karan,26,45000
8,Meena,29,52000
9,Amit,25,40000


In [85]:
df['Salary']=df['Salary'].fillna(df['Salary']).mean()
df

,Name,Age,City,Salary
0,Amit,25,Delhi,41200.0
1,Riya,22,Mumbai,41200.0
2,John,28,Chennai,41200.0
3,Neha,24,Delhi,41200.0
4,Arun,30,Pune,41200.0
5,Riya,22,Mumbai,41200.0
6,Sita,27,Kolkata,41200.0
7,Karan,26,Bangalore,41200.0
8,Meena,29,Delhi,41200.0
9,Amit,25,Delhi,41200.0


In [86]:
df.drop_duplicates()

,Name,Age,City,Salary
0,Amit,25,Delhi,41200.0
1,Riya,22,Mumbai,41200.0
2,John,28,Chennai,41200.0
3,Neha,24,Delhi,41200.0
4,Arun,30,Pune,41200.0
6,Sita,27,Kolkata,41200.0
7,Karan,26,Bangalore,41200.0
8,Meena,29,Delhi,41200.0
